### ISSUE TITLE
Documentação.

### ISSUE THREAD

**Issue by rogeriop1990cv** [alleSilva/courseBot#6]
Reparei que não existe uma README explicando como usa o bot e nem como funcionar ele, recomendo usa esse site https://readme.so/pt/editor pra criar a documentação.

Recomendo criar docker file pra o mysql é redis ou melhor um docker-compose.

**Comment by alleSilva** [comment]
> Reparei que não existe uma README explicando como usa o bot e nem como funcionar ele, recomendo usa esse site https://readme.so/pt/editor pra criar a documentação.
> 
> Recomendo criar docker file pra o mysql é redis ou melhor um docker-compose.

Anotado, qualquer ajuda é bem vinda, principalmemte na parte de docker.
